import{a as S,S as q,i as c}from"./assets/vendor-DQvd0HNi.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&o(i)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function o(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();const M="55062320-0440d879b5463c33572d356a2",P="https://pixabay.com/api/";async function p(a,t=1){const s={key:M,q:a,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:15};return(await S.get(P,{params:s})).data}const m=document.querySelector(".gallery"),f=document.querySelector(".loader"),y=document.querySelector(".load-more"),B=new q(".gallery a",{captionsData:"alt",captionDelay:250});function g(a){const t=a.map(({webformatURL:s,largeImageURL:o,tags:e,likes:r,views:i,comments:v,downloads:w})=>`
<li class="gallery-item">
  <a href="${o}">
    <img src="${s}" alt="${e}" />
  </a>
  <div class="info">
  <p><span class="label">Likes</span><span>${r}</span></p>
  <p><span class="label">Views</span><span>${i}</span></p>
  <p><span class="label">Comments</span><span>${v}</span></p>
  <p><span class="label">Downloads</span><span>${w}</span></p>
</div>
</li>`).join("");m.insertAdjacentHTML("beforeend",t),B.refresh()}function $(){m.innerHTML=""}function h(){f.classList.remove("hidden")}function L(){f.classList.add("hidden")}function b(){y.classList.add("visible")}function d(){y.classList.remove("visible")}const E=document.querySelector(".form"),O=document.querySelector(".load-more");let l="",n=1,u=0;E.addEventListener("submit",async a=>{if(a.preventDefault(),l=a.target.elements["search-text"].value.trim(),!l){c.error({message:"Please enter a search query!"});return}n=1,$(),h();try{d();const t=await p(l,n);if(u=t.totalHits,t.hits.length===0){c.error({message:"Sorry, there are no images matching your search query. Please try again!"});return}g(t.hits);const s=Math.ceil(u/15);n<s?b():d()}catch{c.error({message:"Something went wrong. Try again!"})}finally{L()}});O.addEventListener("click",async()=>{n+=1;try{h();const a=await p(l,n);g(a.hits);const t=Math.ceil(u/15);n>=t?(d(),c.info({message:"We're sorry, but you've reached the end of search results."})):b();const o=document.querySelector(".gallery a").getBoundingClientRect();window.scrollBy({top:o.height*2,behavior:"smooth"})}catch{c.error({message:"Error loading more images"})}finally{L()}});
//# sourceMappingURL=index.js.map
